#!/usr/bin/env python3
from pathlib import Path
import re
import shutil
import sys

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
CUSTOM = ROOT / "wdttsl-custom"


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def write(rel, text):
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def replace_required(text, old, new, label):
    if old not in text:
        raise SystemExit(f"VPNSL 1.0.7 anchor missing: {label}")
    return text.replace(old, new, 1)


# 1.0.7 is deliberately based on the exact, working 1.0.5 routing engine.
# Do NOT apply the 1.0.6 combined-routing patch before this script.
# Android VpnService application selection is an interface-wide filter, so the
# 1.0.6 attempt prevented global IP/file routes from seeing traffic generated by
# non-selected applications. Restore the proven 1.0.5 runtime unchanged.
tun_rel = "app/src/main/java/com/csqtt/client/TunVpnService.kt"
tun = read(tun_rel)
required_runtime = [
    "if (routingSourceMode == RoutingSourceMode.APPLICATIONS)",
    "builder.addAllowedApplication(pkg)",
    "RoutePolicyApplier.apply(builder, routeListStore.loadProfiles())",
]
for marker in required_runtime:
    if marker not in tun:
        raise SystemExit(f"VPNSL 1.0.7 requires exact 1.0.5 runtime marker: {marker}")
if "defaultTarget = RouteTarget.WDTTSL" in tun:
    raise SystemExit("1.0.6 combined runtime leaked into 1.0.7 baseline")

# Promo-style header while keeping the 1.0.5 routing editor and controls.
promo_src = CUSTOM / "PromoRoutingHeader.kt"
promo_dst = ROOT / "app/src/main/java/com/csqtt/client/ui/PromoRoutingHeader.kt"
if not promo_src.is_file():
    raise SystemExit("missing PromoRoutingHeader.kt")
shutil.copyfile(promo_src, promo_dst)

exceptions_rel = "app/src/main/java/com/csqtt/client/ui/ExceptionsTab.kt"
exceptions = read(exceptions_rel)
exceptions = replace_required(
    exceptions,
    "    CsqttScreen {\n        AppSectionCard(",
    "    CsqttScreen {\n        PromoRoutingHeader(\n            mode = routingSourceMode,\n            selectedApps = selectedPackages.size,\n        )\n\n        AppSectionCard(",
    "promo header insertion",
)
exceptions = exceptions.replace(
    'RoutingSourceMode.ROUTE_LISTS to "Маршруты"',
    'RoutingSourceMode.ROUTE_LISTS to "IP / файлы"',
)
write(exceptions_rel, exceptions)

# Version bump.
gradle = read("app/build.gradle.kts")
gradle = re.sub(r'versionCode\s*=\s*\d+', 'versionCode = 1007', gradle, count=1)
gradle = re.sub(r'versionName\s*=\s*"[^"]+"', 'versionName = "1.0.7"', gradle, count=1)
write("app/build.gradle.kts", gradle)

screen_rel = "app/src/main/java/com/csqtt/client/ui/components/CsqttScreen.kt"
screen = read(screen_rel).replace("1.0.5 by Sazhaev-IA", "1.0.7 by Sazhaev-IA")
write(screen_rel, screen)

# Keep the custom VPNSL adaptive launcher icon introduced in 1.0.6.
icon = '''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M54,17 L83,28 L83,49 C83,69 71,83 54,92 C37,83 25,69 25,49 L25,28 Z" />
    <path
        android:fillColor="#FF0474FB"
        android:pathData="M40,39 A5,5 0,1 0,40,49 A5,5 0,1 0,40,39 M68,39 A5,5 0,1 0,68,49 A5,5 0,1 0,68,39 M54,62 A6,6 0,1 0,54,74 A6,6 0,1 0,54,62 M44,44 L64,44 L64,49 L57,62 L51,62 L44,49 Z" />
</vector>
'''
write("app/src/main/res/drawable/ic_launcher_foreground.xml", icon)

# Strong checks that the file/IP path is still the known-good 1.0.5 path.
route_rel = "app/src/main/java/com/csqtt/client/ui/RouteListsSection.kt"
route = read(route_rel)
compiler_rel = "app/src/main/java/com/csqtt/client/routing/RoutePolicyCompiler.kt"
compiler = read(compiler_rel)
checks = {
    "version 1.0.7": 'versionName = "1.0.7"' in read("app/build.gradle.kts"),
    "version code 1007": 'versionCode = 1007' in read("app/build.gradle.kts"),
    "header 1.0.7": '1.0.7 by Sazhaev-IA' in read(screen_rel),
    "promo header": 'PromoRoutingHeader(' in exceptions and promo_dst.is_file(),
    "1.0.5 source selector": 'RoutingSourceMode.APPLICATIONS' in exceptions and 'RoutingSourceMode.ROUTE_LISTS' in exceptions,
    "1.0.5 app runtime": 'if (routingSourceMode == RoutingSourceMode.APPLICATIONS)' in tun,
    "1.0.5 app allow list": 'builder.addAllowedApplication(pkg)' in tun,
    "1.0.5 global file runtime": 'RoutePolicyApplier.apply(builder, routeListStore.loadProfiles())' in tun,
    "1.0.5 compiler default mobile": 'inheritedTarget = RouteTarget.MOBILE' in compiler,
    "no 1.0.6 compiler override": 'defaultTarget:' not in compiler,
    "file import": 'store.importProfile(name, text, RouteTarget.WDTTSL)' in route,
    "manual IP/CIDR": 'IP-адрес или подсеть' in route,
    "BAT export": 'Выгрузить все маршруты (.bat)' in route,
    "domain generator": 'InetAddress.getAllByName(host)' in route,
    "custom launcher icon": 'M54,17 L83,28' in read("app/src/main/res/drawable/ic_launcher_foreground.xml"),
}
failed = [name for name, ok in checks.items() if not ok]
if failed:
    raise SystemExit("VPNSL 1.0.7 verification failed: " + ", ".join(failed))

print("VPNSL 1.0.7: restored exact 1.0.5 file/IP routing + promo UI")
