<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>VPNSL.Windows.Program</StartupObject>
    <AssemblyName>VPNSL.Windows</AssemblyName>
    <RootNamespace>VPNSL.Windows</RootNamespace>
    <Version>1.0.2</Version>
    <FileVersion>1.0.2.0</FileVersion>
    <Product>VPNSL for Windows</Product>
    <Authors>Sazhaev-IA</Authors>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
